services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: network-log-backend
    ports:
      - "5000:5000"
    volumes:
      # Base de données persistante
      - ./data/logs.db:/app/logs.db
      # Logs système (lecture seule)
      - /var/log:/var/log:ro
      # journalctl (lecture seule)
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: network-log-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
